backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: simple #editorial_workflow Allows you to save drafts before publishing them
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "../img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "articles" # Used in routes, e.g., /admin/collections/blog
    label: "articles" # Used in the UI
    folder: "static/articles" # The path to the folder where our blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document
      - { label: "Layout", name: "layout", widget: "hidden", default: "articles"}
      - { label: "Slug", name: "slug", widget: "string", hint: "IMPORTANT : l'adresse de la page, en minuscule, sans espaces!" }
      - { label: "url canonique", name: "canonical", widget: "string", hint: "Laisser vide si identique à slug" }
      - { label: "meta description", name: "meta", widget: "string", hint: "La meta quoi" }
      - { label: "balise title", name: "title", widget: "string"}
      - { label: "h1", name: "h1", widget: "string"}
      - label: Image de couverture
        name: featured_image
        widget: object
        fields:
          - {name: thumbnail, label: Image, widget: image}
          - {name: alt, label: Balise alt, widget: string}
          - {name: legend, label: Légende, widget: string}
      #- { label: "Image de couverture", name: "thumbnail", widget: "image"}
      - { label: "Décalage de l'image de couverture", name: "decalage", widget: "number", default: 0, value_type: "int", min: -100, max: 100, step: 1 }
      - { label: "Date de publication", name: "date", widget: "datetime"}
      - { label: "Tableau (optionnel, pour chaque ligne, séparer les colonnes par des virgules)", name: "tableau", widget: "list", field: {label: ligne, name: ligne, widget: string} }
      - label: 'Section'
        name: 'contenu'
        widget: 'list'
        types:
          - label: "Chapo"
            name: "chapo"
            widget: object
            fields: 
              - { label: "Contenu du chapo", name: "chapocontent", widget: text, hint : "Optionnel"}
          - label: "Titre de section (h2)"
            name: "headingh2"
            widget: object
            default: 'Titre de la section'
            fields: 
              - { label : "Un h2", name : "h2", widget : string, hint : 'Titre de section (h2)'}
          - label: "Titre de section (h3)"
            name: "headingh3"
            widget: object
            default: 'Titre de la section'
            fields: 
              - { label : "Un h3", name : "h3", widget : string, hint : 'Titre (ou sous-titre) de section (h3)'}
          - label: "Bloc de texte"
            name: "textblock"
            widget: object
            fields: 
              - { label: "Corps", name: "body", widget: "markdown" }
          - label: "Encart"
            name: "encart"
            widget: object
            fields: 
              - { label: "Contenu de l'encart", name: "encartcontent", widget: text, hint : "Optionnel"}
          - label: "Images"
            name: "imagesobject"
            widget: object
            fields: 
              - { label: "Images", name: images, widget: list, field: { label: Image, name: image, widget: image }}